[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "super_foo"
author = "kan"
author-email = "pablokan@gmail.com"
classifiers = [ "License :: OSI Approved :: MIT License",]

